config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'overview', to: 'toppages#overview'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
     validates :self_introduction, presence: false, length: { maximum: 1000 }
     mount_uploader :image, ImageUploader
                      
    has_secure_password
    has_many :posts
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_posts, through: :favorites, source: :post
    
    def follow(other_user)
      unless self == other_user
        self.relationships.find_or_create_by(follow_id: other_user.id)
      end
    end

    def unfollow(other_user)
      relationship = self.relationships.find_by(follow_id: other_user.id)
      relationship.destroy if relationship
    end

    def following?(other_user)
      self.followings.include?(other_user)
    end
    
    def favorite(post)
       self.favorites.find_or_create_by(post_id: post.id)
    end

    def unfavorite(post)
      favorite = self.favorites.find_by(post_id: post.id)
      favorite.destroy if favorite
    end

    def is_favorite?(post)
      self.favorite_posts.include?(post)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :edit]

  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 25)
  end

  def show
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts.order(id: :desc), items: 10)
    counts(@user)
    
    @followings = @user.followings.limit(5)
    counts(@user)
    @followers = @user.followers.limit(5)
    counts(@user)
    @likes = @user.favorite_posts.limit(5)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'ユーザを登録しました。'
      redirect_to '/'
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to '/'
    end
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = '正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end
  
  def destroy
  end
  
  def followings
    @user = User.find(params[:id])
    @pagy, @followings = pagy(@user.followings)
    counts(@user)
  end

  def followers
    @user = User.find(params[:id])
    @pagy, @followers = pagy(@user.followers)
    counts(@user)
  end
  
  def likes
     @user = User.find(params[:id])
    @pagy,  @likes = pagy(@user.favorite_posts)
    counts(@user)
  end
  
  private
  
  def set_image
      @image = Image.find(params[:id])
  end
    
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :self_introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/users/_users.html.erb
<% if users.any? %>
<div class="relationships-list">
    <% users.each do |user| %>
    <div class="user-list">
        <% if  user.image.present? %>
           <p><%= link_to image_tag(user.image.url, :alt => 'プロフィール画像'), user_path(user) if user.image? %></p>
        <% else %>
           <p><%= link_to image_tag(gravatar_url(@user), :alt => '未設定時のプロフィール画像'), user_path(user) %></p>
         <% end %>
         <div class="user-box">
            <h5>ユーザー名</h5>
            <%= link_to user.name, user_path(user)  %>
            <h5>プロフィール名</h5>
            <p><%= user.self_introduction %></p>
          </div>
    </div>
    <% end %>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="text-center">
  <h1>プロフィール編集</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
    <%= render 'layouts/edit_error_messages', model: f.object %>
      <div class="mb-3">
        <div class="user-image">
        <%= image_tag @user.image.url, :alt => 'プロフィール写真' if @user.image? %>
        </div>
        <div class="select-image">
        <%= f.file_field :image %>
        </div>
      </div>
      
      <div class="edit-userName mb-3">
        <%= f.label :name, 'ユーザーネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :self_introduction, 'プロフィール' %>
        <%= f.text_area :self_introduction, class: 'form-control', :size=>"60x10" %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'パスワード再確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div>
      <%= f.submit '保存', class: 'btn btn-primary w-100' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="follower-list">
<h3>フォロワー一覧</h3>
<%= render 'users', users: @followers %>

<% if @followers.count == 0 %>
<div class="nil-followers-user">
    <p>現在、あなたをフォローしているフォロワーはいません</p>
</div>
<% end %>

<div class= "pagy">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
</div>

app/views/users/followings.html.erb
<div class="follow-list">
<h3>フォロー一覧</h3>
<%= render 'users', users: @followings %>

<% if @followings.count == 0 %>
<div class="nil-following-user">
    <p>現在、フォローしているユーザーはいません</p>
</div>
<% end %>

<div class= "pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
</div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="favorite-list">
<h3>お気に入り一覧</h3>
<% @likes.each do |post| %>

<div class="post-box">
<p><%= link_to image_tag(post.photo.url, :alt => 'お気に入り登録している写真'), post %></p>

<div class="like-post-information">
<h5>作品名</h5>
<p><%= post.title %></p>

<h5>作者</h5>
<p><%= link_to post.user.name %></p>

<h5>詳細</h5>
<p><%= post.explanation %></p>
</div>
</div>
<% end %>

<% if @likes.count == 0 %>
<div class="nil-like-post">
    <p>お気に入りにしている現在、作品はありません。</p>
</div>
<% end %>
<div class="pagy">
<%== pagy_bootstrap_nav(@pagy) %>
</div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>サインアップ</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/signup_error_messages', model: f.object %>
      <div class="mb-3">
        <%= f.label :name, 'ユーザーネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'パスワード再確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="signup-button">
      <%= f.submit 'サインアップ', class: 'btn btn-primary w-100' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
<% if @current_user == @user %>
<div class="profile">
  <h3><%= @user.name %></h3>
<% if  @user.image.present? %>
  <p><%= link_to image_tag(@user.image.url, :alt => '自分のプロフィール写真') if @user.image? %></p>
<% else %>
  <p><%= link_to image_tag(gravatar_url(@user), :alt => '未設定時のプロフィール写真') %></p>
<% end %>

<div>
<p>プロフィール</p>
</div>
<div class="profile-intorduction">
<p><%= simple_format(@user.self_introduction) %></p>
</div>
<%= link_to "編集", edit_user_path(current_user) %>
</div>
  
  <div class="follow">
    <div class="item">
    <h5>フォローユーザー</h5>
    <%= link_to 'フォロー一覧', followings_user_path(@user)%>
    </div>
    <%= render 'users', users: @followings %>
   </div>
   
   <div class="follower">
     <div class="item">
     <h5>フォロワーユーザー</h5>
     <%= link_to 'フォロワー一覧', followers_user_path(@user) %>
     </div>
     <%= render 'users', users: @followers %>
   </div>
   
   <div class= "favorite">
     <div class="item">
     <h5>お気に入り作品</h5>
     <%= link_to 'お気に入り一覧', likes_user_path(@user) %>
     </div>
     <div class="favorite-posts">
     <% @likes.each do |post| %>
       <p><%= link_to image_tag(post.photo.url, :alt => '自身のお気に入り投稿'), post %></p>
     <% end %>
     </div>
   </div>
  
  <div class="my-posts">
    <div class="item">
  <h5>自身の投稿</h5>
  </div>
  <% if @posts.any? %>
    <div class="my-posts">
      <% @posts.each do |post| %>
        <p><%= link_to image_tag(post.photo.url, :alt => '自分の最新の投稿'), post %></p>
  <% end %>
    </div>
    <div class= "user-show-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    </div>
  <% end %>


<% else %>

<div class="profile">
  <h3><%= @user.name %></h3>
<% if  @user.image.present? %>
  <p><%= link_to image_tag(@user.image.url, :alt => 'プロフィール投稿') if @user.image? %></p>
<% else %>
  <p><%= link_to image_tag(gravatar_url(@user), :alt => '未設定のプロフィール写真') %></p>
<% end %>

<div class="follow-bar"><%= render 'relationships/follow_button',  user: @user%></div>
<div>
<p>プロフィール</p>
</div>
<div class="profile-intorduction">
<p><%= simple_format(@user.self_introduction) %></p>
</div>

</div>
  
  
 <div class="user-posts">
   <div class="item">
  <h5>このユーザーの投稿</h5>
  </div>
  <% if @posts.any? %>
  <div class="user-posts">
  <% @posts.each do |post| %>
    <p><%= link_to image_tag(post.photo.url, :alt => '閲覧しているユーザーの投稿'), post %></p>
  <% end %>
  </div>
  </div>
  <div class= "user-show-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  <% end %>
  

<% end %>

<% else %>
<div class="profile">
  <h3><%= @user.name %></h3>
<% if  @user.image.present? %>
  <p><%= link_to image_tag(@user.image.url, :alt => 'ユーザーのプロフィール写真') if @user.image? %></p>
<% else %>
  <p><%= link_to image_tag(gravatar_url(@user), :alt => '未設定のユーザーのプロフィール写真') %></p>
<% end %>

<div>
<p>プロフィール</p>
</div>
<div class="profile-intorduction">
<p><%= simple_format(@user.self_introduction) %></p>
</div>
</div>
  
  
  <div class="user-posts">
    <div class="item">
  <h5>このユーザーの投稿</h5>
  </div>
  <% if @posts.any? %>
  <div class="user-posts">
  <% @posts.each do |post| %>
    <p><%= link_to image_tag(post.photo.url, :alt => '閲覧しているユーザーの投稿'), post %></p>
  <% end %>
  </div>
  <div class= "logout-user-show-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    </div>
  <% end %>

  <% end %>