config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'overview', to: 'toppages#overview'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
    #検索フォーム
    @q = Post.ransack(params[:q])
    @search_posts = @q.result(distinct: true)
    
    @all_post = Post.all
    @user = User.all
    @posts = Post.order(created_at: :desc).limit(5)
    @favorite_posts = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
    @follower_users = User.find(Relationship.group(:follow_id).order('count(follow_id) desc').limit(5).pluck(:follow_id))
    
    if logged_in?
      @my_posts = current_user.posts.order(created_at: :desc).limit(5)
    end
    
  end
  
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/_search.html.erb
<!-- 検索フォーム -->
  <%= search_form_for @q, url: search_path do |f| %>
    <div class="input-group mb-3">
      <%= f.search_field :title_or_explanation_cont,  class: 'form-control', placeholder: '検索ワード' %>
      <div class="input-group-append">
        <%= f.submit '検索', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <%= render 'search', q: @q, url: search_path %>
  
  <div class="item">
  <h5>最新の投稿</h5>
  <%= link_to '作品一覧', posts_path %>
  </div>
  <div class="flex-container">
    <% @posts.each do |post| %>
    <p><%= link_to image_tag(post.photo.url, :alt => '最新投稿'), post %></p>
  <% end %>
  </div>
  
  <div class="item">
  <h5>人気の投稿</h5>
  </div>
  <div class="flex-container">
    <% @favorite_posts.each do |post| %>
    <p><%= link_to image_tag(post.photo.url, :alt => '人気投稿'), post %></p>
  <% end %>
  </div>
  
  <div class="item">
  <h5>人気のユーザー</h5>
  </div>
  <div class="users">
    <% @follower_users.each do |user| %>
    <% if  user.image.present? %>
      <p><%= link_to image_tag(user.image.url, :alt => 'ユーザーの写真'), user_path(user) if user.image? %></p>
     <% else %>
        <p><%= link_to image_tag(gravatar_url(user), :alt => 'ユーザーの写真'), user_path(user) %></p>
    <% end %>
  <% end %>
  </div>
  
  <div class="item">
  <h5>自分の投稿</h5>
  <%= link_to '自分の投稿一覧', user_path(current_user) %>
  </div>
    <div class="flex-container">
    <% @my_posts.each do |post| %>
      <p><%= link_to image_tag(post.photo.url, :alt => '自分の投稿'), post %></p>
    <% end %>
  </div>
  

<% else %>
  <div class="top-image">
     <h1><%= image_tag 'top-image.png', :alt => 'アプリ概要' %></h1>
  </div>
  
  <%= render 'search', q: @q, url: search_path %>
  
  <div class="item">
  <h5>最新の投稿</h5>
  <%= link_to '作品一覧', posts_path %>
  </div>
  <div class="flex-container">
    <% @posts.each do |post| %>
    <p><%= link_to image_tag(post.photo.url, :alt => '最新投稿'), post %></p>
  <% end %>
  </div>
  
  <div class="item">
  <h5>人気の投稿</h5>
  </div>
  <div class="flex-container">
    <% @favorite_posts.each do |post| %>
    <p><%= link_to image_tag(post.photo.url, :alt => '人気投稿'), post %></p>
  <% end %>
  </div>
  
  <div class="item">
  <h5>人気のユーザー</h5>
  </div>
  <div class="users">
    <% @follower_users.each do |user| %>
     <% if  user.image.present? %>
        <p><%= link_to image_tag(user.image.url, :alt => 'ユーザーの写真'), user_path(user) if user.image? %></p>
     <% else %>
        <p><%= link_to image_tag(gravatar_url(user), :alt => 'ユーザーの写真'), user_path(user) %></p>
     <% end %>
    <% end %>
  </div>
  

<% end %>

app/views/toppages/overview.html.erb
<div class="overview">
    <h3>THE EXPOの使い方</h3>
    <p>作品出展アプリTHE EXPOに関しての基本的な使い方を説明します</p>
    
    <article class="overview-step">
        <div class="overview-toppage">
            <h1><%= image_tag 'overview1.png', :alt => 'アプリを紹介する写真' %></h1>
            <h4>1.基本画面</h4>
            <ol>
                <li>&#9312; ・・・　アカウント登録を行うページに進みます</li>
                <li>&#9313; ・・・　ログインするページに進みます</li>
                <li>&#9314; ・・・　現在、閲覧しているページに進みます</li>
                <li>&#9315; ・・・　最新の一覧を表示しているページに進みます</li>
                <li>&#9316; ・・・　検索をかけて、調べることができます</li>
                <li>&#9317; ・・・　投稿された作品をクリックすると、作品の詳細ページに進みます。</li>
             </ol>
        </div>
        
        <div class="overview-signup">
            <h1><%= image_tag 'overview2.png', :alt => 'アプリを紹介する写真' %></h1>
            <h4>2.サインアップ</h4>
            <ol>
                <li>&#9312; ・・・　ご自身のユーザーネームを記入してください</li>
                <li>&#9313; ・・・　ご自身のメールアドレスを入力してください</li>
                <li>&#9314; ・・・　お考えになったパスワードを入力してください</li>
                <li>&#9315; ・・・　先程、ご記入になりましたパスワードを再度、ご記入してください</li>
                <li>&#9316; ・・・　すべての欄に記入し、間違いがないかご確認された後、サインアップボタンを押していただくと、
                                     アカウント登録が完了します</li>
             </ol>
        </div>
        
        <div class="overview-profile">
            <h1><%= image_tag 'overview3.png', :alt => 'アプリを紹介する写真' %></h1>
            <h1><%= image_tag 'overview4.png', :alt => 'アプリを紹介する写真' %></h1>
            <h4>3.プロフィール</h4>
            <ol>
                <li>&#9312; ・・・　ユーザーネーム</li>
                <li>&#9313; ・・・　プロフィール写真</li>
                <li>&#9314; ・・・　プロフィール欄</li>
                <li>&#9315; ・・・　ここからプロフィールを編集することができます</li>
                <li>&#9316; ・・・　ご自身がフォローしたユーザーを表示します</li>
                <li>&#9317; ・・・　自身をフォローしたユーザーを表示します</li>
                <li>&#9318; ・・・　お気に入り登録した作品を表示します</li>
                <li>&#9319; ・・・　過去にユーザーが投稿した作品を表示します</li>
             </ol>
        </div>
        
        <div class="overview-profile-edit">
            <h1><%= image_tag 'overview5.png', :alt => 'アプリを紹介する写真' %></h1>
            <h4>4.プロフィール編集</h4>
            <ol>
                <li>&#9312; ・・・　プロフィール写真を設定できます</li>
                <li>&#9313; ・・・　ユーザーネームを変更できます</li>
                <li>&#9314; ・・・　プロフィールを編集できます</li>
                <li>&#9315; ・・・　メールアドレスを変更できます</li>
                <li>&#9316; ・・・　ご変更後、パスワードを入力してください</li>
                <li>&#9317; ・・・　同じく先程と同じパスワードを入力してください</li>
                <li>&#9318; ・・・　パスワード入力後、保存ボタンを押すと、正式に編集したものが保存されます</li>
             </ol>
        </div>
        
        <div class="overview-post">
            <h1><%= image_tag 'overview6.png', :alt => 'アプリを紹介する写真' %></h1>
            <h4>5.作品投稿</h4>
            <ol>
                <li>&#9312; ・・・　投稿したい作品を選択します</li>
                <li>&#9313; ・・・　作品名を記入します</li>
                <li>&#9314; ・・・　詳細を記入して、見てもらいたいポイントなどを書いてみましょう</li>
                <li>&#9315; ・・・　すべて記入が終わったのを確認した後、投稿ボタンをクリックすると投稿されます</li>
             </ol>
        </div>
        
        <div class="overview-last">
            <h4>さいごに</h4>
            <p>このアプリはアーティストや美術家、写真家など、作品を作成する方の為に作成しました
               ご自身が作成した絵画や芸術品,Photoshopやillustratorなどで加工した画像などを
               写真に撮ったり、保存をして投稿してみてください
               また、フォロー機能やお気に入り機能など、ほかにも色々と機能があります
               使いながら、ご自身なりの楽しみ方を見つけてみてください
               それではTHE EXPOの世界をお楽しみください</p>
        </div>
        
    </article>
  </div>