config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'overview', to: 'toppages#overview'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :photo, PhotoUploader
    
    validates :photo,  presence: true
    validates :title, presence: true, length: { maximum: 50 }
    validates :explanation, presence: false, length: { maximum: 1000 }
    
    has_many :favorites, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy ]
  before_action :current_user, only: [:destroy, :edit, :new]
  before_action :require_user_logged_in, only: [:edit]
  before_action :set_search
  #before_action :correct_user, only: [:edit, :new]
  


  # GET /posts or /posts.json
  def index
     @pagy, @posts = pagy(Post.order(id: :desc))
  end

  # GET /posts/1 or /posts/1.json
  def show
    
  end

  # GET /posts/new
  def new
    @post = Post.new
    if @post.user == current_user
      redirect_to '/'
    end
  end

  # GET /posts/1/edit
  def edit
  @post = Post.find(params[:id])
    if @post.user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = '作品を投稿しました。'
      redirect_to root_url
    else
      @pagy, @posts = pagy(current_user.posts.order(id: :desc))
      flash.now[:danger] = '作品の投稿に失敗しました。'
      render 'posts/new'
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:success] = '正常に更新されました'
      redirect_to @post
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:success] = '作品を削除しました。'
    redirect_to("/")
  end
  
  def search
    @pagy,@search_posts = pagy(@q.result(distinct: true).order(id: :desc), items:10)
    @search_posts.count
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:photo, :title, :explanation)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      unless @post
        redirect_to root_url
      end
    end
    
    def set_search
      @q = Post.ransack(params[:q])
    end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="post-form">
<%= form_with(model: post) do |form| %>
  <%= render 'layouts/post_error_messages', model: form.object %>

  <div class="photo">
    <%= form.label '作品' %>
    <%= form.file_field :photo, id: "post_作品" %>
  </div>
  
  <div class="title">
    <%= form.label '作品名' %>
    <%= form.text_field :title, id: "post_作品名"  %>
  </div>
  
  <div class="introduction">
    <%= form.label '詳細' %>
    <%= form.text_area :explanation, id: "post_詳細"  %>
  </div>

  <div class="actions">
    <%= form.submit '投稿', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>編集ページ</h1>

<%= render 'form', post: @post %>

<%= link_to '見る', @post %> |
<%= link_to '戻る', posts_path %>

app/views/posts/index.html.erb
<h3>作品一覧</h3>
<div class="all-post">
      <% @posts.each do |post| %>
      <div class="post-box">
      <p><%= link_to image_tag(post.photo.url, :alt => '一覧時の作品の写真'), post  %></p>

     <div class="all-post-information">
     <h5>作品名</h5>
     <p><%= post.title %></p>

    <h5>作者</h5>
    <p><%= link_to post.user.name, user_path(post.user) %></p>
    
    <h5>詳細</h5>
    <p><%= post.explanation %></p>
    </div>
    </div>
      <% end %>
      <div class="post-index-pagy">
      <%== pagy_bootstrap_nav(@pagy) %>
      </div>
</div>

app/views/posts/new.html.erb
<div class="post-form">
<h1>作品投稿</h1>

<%= render 'form', post: @post %>
</div>

app/views/posts/search.html.erb
<%= render 'toppages/search', q: @q, url: search_path %>

<div class="search-list">
  
<% @search_posts.each do |post| %>
<div class="post-box">
<p><%= link_to image_tag(post.photo.url, :alt => '検索でヒットした投稿'), post %></p>

<div class="search-post-information">
<h5>作品名</h5>
<p><%= post.title %></p>

<h5>作者</h5>
<p><%= link_to post.user.name,  user_path(post.user) %></p>

<h5>詳細</h5>
<p class="search-post-explanation"><%= post.explanation %></p>
</div>
</div>
<% end %>

<% if @search_posts.count == 0 %>
  <div class="search-nil">
  <p>お探しの作品は見つかりませんでした</p>
  </div>
<% end %>

<div class="search-pagy">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

</div>

app/views/posts/show.html.erb
<% if logged_in? %>
<% if current_user == @post.user %>
<div class="show-post">
<p><%= image_tag @post.photo.url, :alt => '自分の作品' if @post.photo? %></p>


<h4>作品名</h4>
<p><%= @post.title  %></p>


<div class="post-user">
<h4>作者</h4>
 <p><%= link_to @post.user.name,  user_path(@post.user)%></p>
 </div>
 
 
<div class="post-explanation">
<h4>詳細</h4>
<div class="post-explanation-p">
<p><%= simple_format(@post.explanation) %></p>
</div>
</div>



<%= link_to '編集', edit_post_path(@post) %> |
<%= link_to "削除", @post, method: :delete, data: { confirm: "削除しますか？" } %> |
<%= link_to '戻る', '/' %>

</div>

<% else %>
<div class="show-post">

<p><%= image_tag @post.photo.url, :alt => '他者の作品' if @post.photo? %></p>

<h4>作品名</h4>
<p><%= @post.title %></p>

<div class="post-user">
<h4>作者</h4>
 <p><%= link_to @post.user.name,  user_path(@post.user)%></p>
 </div>
 <div class="postpage-follow-bar"><%= render 'relationships/postpage_follow_button',  user: @post.user %></div>
 
 
<div class="post-explanation">
<h4>詳細</h4>
<div class="post-explanation-p">
<p><%= simple_format(@post.explanation) %></p>
</div>
</div>


<div class~"favorite-button">
<p><%= render 'favorites/favorite_button', post: @post %></p>
</div>

<div class="bpostpage-back">
<%= link_to '戻る', '/' %>
</div>
</div>
<% end %>


<% else %>
<div class="show-post">
<p><%= image_tag @post.photo.url, :alt => '未ログイン時の他社の作品' if @post.photo? %></p>


<h4>作品名</h4>
<p><%= @post.title  %></p>


<div class="post-user">
<h4>作者</h4>
 <p><%= link_to @post.user.name,  user_path(@post.user)%></p>
 </div>
 
 
<div class="post-explanation">
<h4>詳細</h4>
<div class="post-explanation-p">
<p><%= simple_format(@post.explanation) %></p>
</div>
</div>

<div class="bpostpage-back">
<%= link_to '戻る', '/' %>
</div>
</div>

<% end %>