config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'search', to: 'posts#search'
  get 'overview', to: 'toppages#overview'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/_edit_error_messages.html.erb
<% if model.errors.any? %>
  <div id="edit_error_explanation" class="alert alert-warning">
    <div class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid ps-5 pe-5 pt-3">
            <a class="logo" href="/"><%= image_tag 'logo.png', :alt => 'アプリロゴ' %></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <% if logged_in? %>
                <div class="btn-group">
                <ul class="navbar-nav">
                    <li class="nav-item"><%= link_to '概要', overview_path, class: 'nav-link overview-nav' %></li>
                    <li class="ms-3"><%= link_to '投稿', new_post_path, class: 'nav-link post-nav' %></li>
                </ul>
            <button type="button" class="navbar-btn btn btn-dark dropdown-toggle " data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
                <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %></li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
            </div>
                <% else %>
                <ul class="navbar-nav">
                    <li class="nav-item"><%= link_to '概要', overview_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to 'サインアップ', signup_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
                </ul>
            <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_post_error_messages.html.erb
<% if model.errors.any? %>
  <div id="post_error_explanation" class="alert alert-warning">
    <div class="new-post">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_signup_error_messages.html.erb
<% if model.errors.any? %>
  <div id="signup_error_explanation" class="alert alert-warning">
    <div class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>THE EXPO <作品出展アプリ></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"> 
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <div class="wrap">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    </div>
  </body>
</html>